name: grocery_store
description: A new Flutter project.
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_card: ^1.1.0
  carousel_pro: ^1.0.0
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.2
  cupertino_icons: ^1.0.0
  extended_image: ^1.3.0
  firebase_analytics: ^6.1.0
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  firebase_dynamic_links: ^0.6.1
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.6
  flutter_credit_card: ^0.1.3
  flutter_share: ^1.0.3
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.10.0
  full_screen_image: ^1.0.2
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.5
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  path_provider: ^1.6.22
  shared_preferences: ^0.5.12+2
  shimmer: ^1.1.2
  smooth_star_rating: ^1.1.1
  stripe_payment: ^1.0.8
  transparent_image: ^1.0.0
  uuid: ^2.2.2
  razorpay_flutter: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/banners/
    - assets/banners/easy_returns.svg
